language: java
jdk:
  - oraclejdk8
  - openjdk8

install: true

script: 
- mvn -e -q clean install -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true
